### ISSUE TITLE
Inconsistent processor input files - difficulty getting started

### ISSUE THREAD

**Issue by MoretonBayKiting** [stefanino-ch/lepg-py#3]
Stefanino, Thanks for the GUI to Pere's LEParagliding.

In order to get familiar with it I have installed and opened Pere's BHL7-22/leparagliding.txt (from http://laboratoridenvol.com/projects/BHL7/bhl7.en.html).  (I renamed this leparagliding_Orig.txt).  Although it has 
	number of cells: 33; Number of ribs: 34
the wing view shows 28 cells (either with or without running Processor/Run Processor).  Should I expect to see 33 cells?  Do I need to run another process to get these consistent? 
If I save the processor file (Processor/Save Processor File As...) to leparagliding2.txt there are still 28 cells.  If I then open leparagliding2.txt, the app crashes.  Log file attached. (logfileGood.txt is the log after running with the original input file.)  Having examined differences between the two parameter files (ie leparagliding_Orig.txt and leparagliding2.txt, there are many formatting differences.  For example, the original drawing scale is 1.0 whereas the rewritten one is 1. .  Most other differences appear (VSCode, compare selected files) to be white space differences.

bhlnm-4p.txt, which is written to the processor folder, C:\D\NonSML\WK\AutoKite\SS\PG\LEPG_PY\processors\lep-3.19-win64\lep (ref configFile.txt), is empty.  

[logfile.txt](https://github.com/stefanino-ch/lepg-py/files/14215643/logfile.txt)
[configFile.txt](https://github.com/stefanino-ch/lepg-py/files/14215644/configFile.txt)
[leparagliding_Orig.txt](https://github.com/stefanino-ch/lepg-py/files/14215645/leparagliding_Orig.txt)
[leparagliding2.txt](https://github.com/stefanino-ch/lepg-py/files/14215646/leparagliding2.txt)
[logfileGood.txt](https://github.com/stefanino-ch/lepg-py/files/14215673/logfileGood.txt)

**Comment by MoretonBayKiting** [comment]
I see that the BHL7-22 input file I used includes "* Input data file (leparagliding 3.17+)*".  I understand that there can be forward compatibility problems.  Could you provide an input file that you know works with LEPG_PY.  If I get that working, I should be able to compare with others and modify that.

**Comment by stefanino-ch** [comment]
Good catch, you've found a bug. 
Should be fixed now, you will find an new Version to download here: https://github.com/stefanino-ch/lepg-py/tree/latest/distribution/dist-win64

Some additional informations. 

- lepg-py should read all data files back to lep version 15. However if you save the data, always the syntax of the current processor will be used. So lepg-py reads old files, but the files saved by lepg can usually not be used with older processors. 

- The design you have used to test is based on special airfoil definitions. Got to Processor-> Airfoil you will see the names of the files. For the current example the filenames are gnuPSFtube.txt and bhlnm-4p.txt. COPY those two files into the directory where the processor is saved. 

- After running the processor with Processor-> Run Processor a window opens showing the output of the processor itself. Check this log properly. If a file will be missing you wild find at the very top of the log lines like: 
```
Microsoft Windows [Version 10.0.19045.3803]
At line 2661 of file leparagliding.f (unit = 24, file = 'bhlnm-4p.txt')
(c) Microsoft Corporation. Alle Rechte vorbehalten.
Fortran runtime error: End of file

(venv) C:\Users\user\sw-dev\lepg-py\lepg-py\src>cd C:\Users\user\sw-dev\lepg-py\lepg-py\src\processors\lep-3.19-win64\lep
Error termination. Backtrace:
#0  0xffffffffffffffff in ???
(venv) C:\Users\user\sw-dev\lepg-py\lepg-py\src\processors\lep-3.19-win64\lep>C:/Users/user/sw-dev/lepg-py/lepg-py/src/processors/lep-3.19-win64/lep/lep-3.19-win64.exe
#1  0xffffffffffffffff in ???
```
In line two it tells you that there is a missing file named bhlnm-4p.txt. The many question marks on the lines below are usually also an indicator that there is something wrong. 

Hope this helps.

**Comment by MoretonBayKiting** [comment]
Stefanino,
I downloaded that file but it was assessed to be invalid by WinZip.  It also appears to be an old version:
![image](https://github.com/stefanino-ch/lepg-py/assets/38276781/5be40ca5-8978-4d50-8da5-1fbcfd12c3b9)
Could you check that it is correct?

**Comment by stefanino-ch** [comment]
3.19 is latest and greatest you get as stable version now. Currently I'm working to get the changes for 3.20 implemented, 3.21T was never released officially and since dec 2023 there's a 3.23.
If you want to get familar with lepg then 3.19 is still a pretty good version. The main features are already all in there. Newer versions will bring features like calculation for different line materials and types on the same glider, xflir simulation parameters and even more sophisticated things used by experienced users. 

I checked before the .zip on the server. Download, ectraction and simulation run seems all to be fine. The download might be a liiittle bit tricky. 
Can you please follow the steps below and check again?
Click on the filename.
![download-step-1](https://github.com/stefanino-ch/lepg-py/assets/56797041/2aa12fb7-a946-41ff-9e7b-e5722606b8a0)

A new page opens, complaining about the file is too big to be displayed. 
Click here on "raw download". 
![download-step-2](https://github.com/stefanino-ch/lepg-py/assets/56797041/053e7eec-5aeb-4b61-9289-6f41176e9d94)

**Comment by MoretonBayKiting** [comment]
Thanks Stefanino.  My apologies, that was my error in not downloading the large compressed file.

But I'm afraid it crashes when I run processor.  The log, not saved, shows (as per screen shot attached):
_Running mode: Frozen/executable
Traceback (most recent call last):
  File "gui\MainWindow.py", line 880, in proc_run
  File "enum.py", line 787, in __getattr__
AttributeError: Ok_

Input processor file (leparagliding7_36AR7.txt) and log files (including leparagliding.txt) also attached.
![LEPG_PY_Screen](https://github.com/stefanino-ch/lepg-py/assets/38276781/90246b60-91a0-47c9-88f3-7be1fc1a7ec4)
[leparagliding.txt](https://github.com/stefanino-ch/lepg-py/files/14233740/leparagliding.txt)
[logfile.txt](https://github.com/stefanino-ch/lepg-py/files/14233741/logfile.txt)
[leparagliding7_36AR7.txt](https://github.com/stefanino-ch/lepg-py/files/14233742/leparagliding7_36AR7.txt)

**Comment by stefanino-ch** [comment]
Hey
Are you shure you have configured the processor executable?
I will get the error message if I try to start the processing with no processor setup. 

Start lepg-py go into Setup->Both Processors and select the executables for the pre- and the processor. 

The compatible executables are part of the installation, but as the full path must be configured (starting with e.g. c:/....) the full path might change. 
As soon you're within the downloaded and extracted folder the path would be: 
.......lepg-win64-V3.20.1-stable/processors/lep-3.19-win64/pre1.6/pre-1.6-win64.exe
.......lepg-win64-V3.20.1-stable/processors/lep-3.19-win64/lep/lep-3.19-win64.exe

As originally developed lepg-py should complain about a not found processor, it looks like I need to fix another bug. 
Sorry for the inconvinience. 

If you want, you can just go for 3.20.2 (https://github.com/stefanino-ch/lepg-py/tree/stable/distribution/dist-win64) where the bug has been fixed.

**Comment by MoretonBayKiting** [comment]
Thanks Stefanino.  
My apologies - it was my error not to setup the processors.  But perhaps, as you've done, worth capturing such (operator) error in any case.  Thank you.  I used version 3.20.2 this morning.
The integrated DXF viewer is great.  I'm running a rather old machine with only 4Gb of memory.  It struggles with other DXF viewers I've used.  Although it is still slower than I'd like, what you've integrated is much better than the others I've used.
This is probably a request that should go to Pere (I know he is very busy so won't be able to address it any time soon), but can the DXF files be simplified/broken out?  My colleague who will cut material for a glider wrote the following:
_DXF files are best kept small, one for ribs, one for skin panels.
Preferably with pen and cut separate.
Laser cutter program uses SVG files with layers for cut and pen._
Arnaud Martinez also suggested the following: "_I recommend to disable the ballooning when it comes to LEP 3D output export._"  I've not been able to determine how to do that.  Is it possible in LEPG_PY?
If these latter points should be in separate issues, feel free to move them.
Thanks again for your help.

**Comment by stefanino-ch** [comment]
Hey 
Good to hear that everything works now. I just published also a Linux version with the latest fixes. 

I can forward your request about changing data files to Pere, all the output ist driven py the processors, therefore Pere is the one who can unfluence this. 

Not sure what dou you mean with the ballooning. In general my piece of SW is just an editor helping to create a well structured file afterwards used by Pere's processor. So if the [official lep doc provided by Pere](http://laboratoridenvol.com/leparagliding/manual.en.html) provides such an option you will find it also in my editor.
